name: Deploy 1

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Init new repo in dist folder and commit generated files
      run: |
        cd build
        git init
        git add -A
        git config --local 3086764005@qq.com "action@github.com"
        git config --local babycrocodileschnappi "GitHub Action"
        git commit -m 'deploy'

    - name: Force push to destination branch
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.DEPLOY_SECRET }}
        branch: gh-pages
        force: true
        directory: ./build

