name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Installing NPM packages
        run: npm ci

      - name: Build React App
        run: npm run build

      - name: Uploading production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Downloading artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./build

      - name: Deploying to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_SECRET }}
          publish_dir: ./build

      # - name: Init new repo in dist folder and commit generated files
      #   run: |
      #     cd build
      #     git init
      #     git add -A
      #     git config --global user.email "action@github.com"
      #     git config --global user.name "GitHub Action"
      #     git commit -m 'deploy'
      # - name: Force push to destination branch
      #   uses: ad-m/github-push-action@v0.5.0
      #   with:
      #     github_token: ${{ secrets.DEPLOY_SECRET }}
      #     branch: gh-pages
      #     force: true
      #     directory: ./build
